pipeline {
   agent any

   stages {
      stage('Run the aws instance with selenoid') {
         steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
            accessKeyVariable: 'AWS_ACCESS_KEY_ID',
            credentialsId: '',
            secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
            sh "terraform init"
            sh "terrafrom plan"
            sh "terraform apply -input=false -auto-approve"
            }
         }
   }
}
}
